name: build
on:
  push:
    branches:
      - master
      - release/*
      - feature/*
      - hotfix/*

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13, 1.14]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        env:
          AgentID: ${{ secrets.DINGTALK_AGENT_ID }}
          AppKey: ${{ secrets.DINGTALK_APP_KEY }}
          AppSecret: ${{ secrets.DINGTALK_APP_SECRET }}
          UserID: ${{ secrets.DINGTALK_USER_ID }}
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Test Coverage Report
        run: bash <(curl -s https://codecov.io/bash)